### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [MIERUNE/qgis-plugx-plugin#158]
# Problem

Please fix the plugin homepage to reference a dedicated page to the repo or the github repo as that page doesn't look like it's dedicated to the plugin

**Comment by Kanahiro** [comment]
@NyakudyaA Thanks for reviewing.
Is that okay?
https://github.com/MIERUNE/qgis-plugx-plugin/blob/main/metadata.txt

![スクリーンショット 2023-10-23 17 49 17](https://github.com/MIERUNE/qgis-plugx-plugin/assets/20744195/1668e8de-61f0-4ac3-a0a6-069a3ec9e3c1)
