### ISSUE TITLE
Make various QGIS Project for test

### ISSUE THREAD

**Issue by xinmiaooo** [MIERUNE/qgis-plugx-plugin#21]
- project should be saved in: https://drive.google.com/drive/u/1/folders/1JLK6I8kFxW384Gyl6IbvfFYTE_UrebOm

- [x] cover all symbol types: https://www.notion.so/mierune/Symbol-Specification-d7801b550b23418ab45e4062bb6090b5
- [x] all type raster
- [ ] edge case (CRS, data...)

**Comment by bordoray** [comment]
End with release 1.0.0
